# -*- coding: utf-8 -*-
"""PolarityReturn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13gPgm2484HDwNN7s9uK4E2bJjxCLNrcF
"""

from textblob import TextBlob
import sys
tb = TextBlob(sys.argv[1])
print(tb.sentiment.polarity)

